version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5335:5432"
    volumes: 
    
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "your_username"]
      interval: 10s
      timeout: 5s
      retries: 5
  ollama:
    image: ollama/ollama:latest  # Use the latest Ollama image
    container_name: ollama
    ports:
      - "11434:11434"  # Map port 11434 for external access
    volumes:
      - ollama_data:/root/.ollama  # Persistent storage for Ollama data
    restart: unless-stopped
    entrypoint: ["ollama", "serve"]  # Start the Ollama app


  rabbitmq:
    image: rabbitmq:3-management
    container_name: app_rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: user  # Default username
      RABBITMQ_DEFAULT_PASS: password  # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
#Comment
volumes:
  pgdata:
  rabbitmq_data:
  ollama_data:
    driver: local
